services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    image: laravel-app
    depends_on:
      db:
        condition: service_healthy
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  db:
    image: mysql:8.4.2
    ports:
      - 3306:3306
    platform: linux/arm64
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: product_registry
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
